### PR TITLE
[ Controller support add] Hori PS4 Tatacon

### PR DESCRIPTION
**Pull request by italobechepeche**
Added support for Hori PS4 tatacon, it recognized correctly and it's working, don't know if more tests are needed or some changes, but it's working.

### CODE REVIEW

**Comment by cathery** [comment]
It uses the same event index as the DS4 event. This will override the ds4 event and render dualshock 4 controllers unrecognisable

**Comment by italobechepeche** [comment]
Do you have a tip how can I fix that? Because the `usbHsCreateInterfaceAvailableEvent` only accept indexes from 0 to 2 and all of them is already in use by `DS3EVENT_INDEX, DS4EVENT_INDEX, ALLEVENT_INDEX`

**Comment by cathery** [comment]
i don't

**Comment by amit27592** [comment]
Can't this also be controlled via a global config flag? Granted it's a little cumbersome but people don't generally use all the supported controllers all at the same time.

**Comment by cathery** [comment]
Yes, but it will only take so long until the global config gets bloated. I'm planning to make a homebrew application that will let you pick which controllers to recognize. This app will also erase the need to manually change the config files completely. :)

**Comment by cathery** [comment]
For now, if you really wish to use the Tatacon controller, you can build italobechepeche's master branch yourself. It uses the basic switch homebrew development tools, and the building instructions are in the README.

**Comment by p-sam** [comment]
fwiw i've been using a patch for a while to allow both DS4 gens and a certain hori mini ds4 controller

[sys-con-hori.txt](https://github.com/cathery/sys-con/files/4502992/sys-con-hori.txt)

Using a sony vendor filter with no product id allowed to merge the DS3/DS4 filters into one, so one for the Hori vendor id could be made. Filtering also happens later in CheckForInterfaces. Are there any downsides to that solution?

I'd say it probably should stay at just a fork/patch, since kinda like you said, it will only take so long before other controllers/vendor will surface and need support. But I'm willing to PR anything if you think there's stuff to keep.

**Comment by cathery** [comment]
I had no idea this worked. Just confirmed. I'll implement this immediately. Thank you for letting me know

**Comment by italobechepeche** [comment]
I'll close this PR for now, if you want play with HORI PS4 Tatacon you can build my forked version.

**Pull request closed without merging**
